cookieによるユーザー情報を個別管理
Replay95/TODO-List-Backend pull request #4
Opened 2024-08-19 15:00 UTC by Replay95

# 変更内容h1
* cookieによるユーザー情報の個別管理機能を実装
* 上記に付随してユーザー情報ごとにTODOリストの個別管理機能を実装

# 補足事項h2
* プログラムの実際の挙動は`Discord`上に添付

確認お願いします

2024-08-20 05:27 UTC, kei95 requested changes

2024-08-20 05:27 UTC, kei95 commented on index.js
> +    res.status(500).json({ message: "サーバー側でエラーが発生しました" });
良い変更 👍 エラーの際もこうやってメッセージというプロパティー付きのオブジェクトとして返すようにすることでFEでエラーをハンドルする際にどんなエラーがくるか予想つくようになる

2024-08-20 05:27 UTC, kei95 commented on index.js
> +      if (errors) throw errors;
@kou-96の[コメントと一緒](https://github.com/kou-96/todolist-backend/pull/4#discussion_r1722698594)。ChatGPTは`try/catch`の使い方がわからんのか？

2024-08-21 02:48 UTC, Replay95 commented on index.js
> +      if (errors) throw errors;
いや、これは私が`try/catch`の使い方の理解不足だったパターンですね
`try/catch`の中に条件分岐した`if文`をいれる発想がなかったです
修正します

2024-08-21 03:35 UTC, Replay95 commented
指摘箇所を修正しました
確認お願いします

2024-08-21 19:41 UTC, kei95 requested changes
エラーのハンドリングだけ更新しようか。他はいい感じ

2024-08-21 19:41 UTC, kei95 commented on index.js
> +      res.status(401).json({ message: "パスワードが違います" });
このif文、やってる事としてはいい事なんだけど認証においてエラーのメッセージで何が間違っているかをユーザーに教えるのは実はセキュリティー上アンチパターン。

ハッカーがなりすましてemailやpasswordで色々試している時にどっちかが合ってるとヒントになってしまうからで、基本的には`401`で"入力情報に誤りがあります"みたいなどっちが間違っているかわからないメッセージを送るのが基本的に良しとされている方法

cc: @kou-96

2024-08-21 19:41 UTC, kei95 commented on index.js
> +app.post("/api/login", async (req, res) => {
前回`acync`入ってなかったのか笑
これは大事な変更やね

2024-08-22 02:24 UTC, Replay95 commented
エラーハンドリングの内容を更新しました

2024-09-02 02:53 UTC, kei95 approved these changes
素晴らしい👍

2024-09-02 07:11 UTC, Replay95 commented
gitのレポジトリ上からnode_modulesを削除し、以後コミットされないようにしました
確認をお願いします

2024-09-02 10:48 UTC, kei95 approved these changes

2024-09-02 12:41 UTC, merged